name: Quality Checks
on:
  push:
    # Only run these quality checks for non-main branches. Quality checks for
    # main are run elsewhere.
    branches-ignore: [main]
jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "âš™ï¸ Install dependencies"
        run: pip3 install .[all]
      - name: "ğŸ§¹ Running quality checks"
        run: |
          make quality
          python -m pytest
